---
roles:
  - name: dpanel.cloud-provider
    src: https://github.com/devetek/dpanel-resource-deploy

collections:
  - name: ansible.posix
  - name: community.mysql
  - name: community.general
  - name: google.cloud