---

- hosts: ansible_inventory
  vars:
    message: "Built!"
  tasks:
    - name: Prints "Built!" in file.
      shell:  |
        echo "{{ message }}" > ~/output-build
        cat ~/output-build
  # roles: