---
- hosts: all
  become: true

  roles:
    - role: robertdebock.users
      tags:
        - user
    - role: devetek.mariadb
      tags:
        - mariadb
    - role: geerlingguy.php-versions
      tags:
        - php
    - role: geerlingguy.php
      tags:
        - php
    - role: geerlingguy.composer
      tags:
        - composer
    - role: devetek.laravel
      tags:
        - laravel
    - role: devetek.phpfpm_pool
      tags:
        - phpfpm
    - role: devetek.build
      tags:
        - build
    - role: devetek.deploy
      tags:
        - deploy
    - role: devetek.caddyserver
      tags:
        - caddyserver
