---

- hosts: all
  become: true

  roles:
    - role: robertdebock.users
      tags:
        - robertdebock.users
    - role: devetek.mariadb
      tags:
        - mariadb
    - role: geerlingguy.php-versions
      tags:
        - php
    - role: geerlingguy.php
      tags:
        - php
    - role: devetek.wpcli
      tags:
          - wordpress
    - role: devetek.wordpress
      tags:
        - wordpress
    - role: devetek.phpfpm_pool
      tags:
        - phpfpm
    - role: devetek.build
      tags:
        - build
    - role: devetek.deploy
      tags:
        - deploy
    - role: devetek.caddyserver
      tags:
        - caddyserver