---

- hosts: ansible_inventory
  vars:
    message: "Deployed!"
  tasks:
    - name: Prints "Deployed!" in file.
      shell:  |
        echo "{{ message }}" > ~/output-deploy
        cat ~/output-deploy
  # roles: