---

- hosts: ansible_inventory
  vars:
    message: "New Version!"
  tasks:
    - name: Prints "New Version!" in file.
      shell:  |
        echo "{{ message }}" > ~/output
        cat ~/output
  # roles: